### ISSUE TITLE
sus::error::Error

### ISSUE THREAD

**Issue by danakj** [chromium/subspace#324]
Using Result in any complex way suddenly requires good Error types.

How do we make errors that all share an API? Inheritance like Iterators probably.
We can use virtual more freely in error handling paths if needed.

We need error conversion as well, which is already possible through [`sus::ops::try_preserve_error`](https://github.com/chromium/subspace/blob/199028415fb4bcfee86f3af5f7272ebe15fe707e/sus/ops/try.h#L178-L191)

The Results returned in [`subdoc/lib/gen`](https://github.com/chromium/subspace/tree/199028415fb4bcfee86f3af5f7272ebe15fe707e/subdoc/lib/gen) are a good example. The majority of functions return `MarkdownToHtmlError` but the root generate function needs to return either `std::error_code` wrapped in `GenerateFileError` or the `MarkdownToHtmlError`.

Secondly, there's a lot of boilerplate in returning results in this directory, which hopefully https://github.com/chromium/subspace/issues/299 can help with. But it will need to be able to convert the errors too. So all Errors should be convertible to some generic thing (`Box<sus::error::DynError>`).

Thirdly, there's a bunch of choice boilerplate when the result wants to finally be received and handled, but probably not much to do for that until C++ gets matchers.

### Tasks
- [x] Create the Error concept https://github.com/chromium/subspace/pull/328
- [x] Make our various errors into Error types (int conversion error, anything that we put in a Result error slot)
- [x] Make the top Subdoc generate functions return Box<DynError> instead of a Choice type. The message generation gets to move into the ErrorImpl implementation. It could keep the underlying source Error too.
- [x] Explain when to use `DynError` and when to make your own error supertype. Make an example of an error supertype that can be downcasted.

**Comment by danakj** [comment]
I think due to https://github.com/chromium/subspace/issues/333#issuecomment-1692369886 `DynError` has to go.

There is no way to downcast safely from a `DynError` to a specific error without RTTI, and we don't want to rely on RTTI. Large projects like Chromium and LLVM disable it.

Unlike Rust, C++ has its own way to express the type erasure and it's inheritance. So if an application wants to make its errors able to downcast it will need to provide its own type-erased base class.

`Box<DynError>` is special cased in Rust to construct from an `Error` but in C++ then what we need instead is that `Box<SuperClass>` can be constructed from `Subclass`, and there's no Error-ness involved at all there.

Then:
- apps can opt into a generic error type and provide downcast traits for it as needed.
- Error can still be applied to types you don't control like enums and std::error_code

Also the `source()` is problematic because it has to return a type-erased error to be part of the type-erased error API. So without `DynError` we could instead say that the `source()` just returns an `Option<T: Error const&>`, or we could just get rid of it and let the application domain put whatever api they want on their root error types as desired.

If we force the error type to return `Option<T: Error const&>` then the root generic type in an application needs to return itself which makes a cyclical dependency to resolve to determine if it satisfies Error.

As such, I think there's no room for DynError _or_ for source() for the `Error` concept.

**Comment by danakj** [comment]
The thing to think about then is what if sus::foo() returned an `Error` and Subdoc wanted to return it from the `source()` of a `GenerateError`? What can it turn it into? Don't we need a `DynError` just for that scenario, passing errors across API boundaries? In that case you don't need to downcast anymore, it could be literally any error really. The downcast would be for debugging on the `GenerateError`, but not its source...?

**Comment by danakj** [comment]
Ok I think this is a matter of writing documentation explaining good practices. And explicitly *not* supporting `Downcast` for `DynError`

If you want to be able to get back your error type, you should make your own generic error base class and support `Downcast` from it. If you want to propagate a source error with more type information, then you should make your error types hold it in a well-typed way and give access to it. If you just want to pass along an error (and its sources) to read the messages from them, then DynError is fine.
